### ISSUE TITLE
Версия guzzlehttp/guzzle

### ISSUE THREAD

**Issue by Rapp-colince** [avangardDeveloper/Avangard-PHP-Lib#3]
В composer.json указана версия "guzzlehttp/guzzle": "^6.4".
Можно ли не ограничивать версию сверху? На моем проекте сейчас требуется "guzzlehttp/guzzle": "7.2", поэтому проблемы с совместимостью

**Comment by avangardDeveloper** [comment]
На данный момент мы не можем гарантировать корректную работу с версией >=7.0. Взяли задачу по подъему версий в работу. А на данный момент рекомендуем вам, чтобы не ждать, сделать fork репозитория и поднять версию у себя.
